# Generated by Django 6.0.4 on 2026-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('groceries', 'Groceries'), ('leisure', 'Leisure'), ('electronics', 'Electronics'), ('utilities', 'Utilities'), ('clothing', 'Clothing'), ('health', 'Health'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
